name: Sync Markdown to Notion

on:
  push:
    paths:
      - '**.md'  # Mỗi khi có file .md được push

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./ky-nam-gpt-core

      - name: Upload Markdown to Notion
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
        run: node uploadMarkdownToNotion.js
        working-directory: ./ky-nam-gpt-core
